# Testing Factor Model Assignment

#### John Crist, Walker Hills, Walter Mitchell, Wyatt Nechtman, Ken Stelzer

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [7]:
five_factor = pd.read_csv('F-F_Research_Data_5_Factors_2x3.csv', skiprows=3)
five_factor.columns = ['date', 'MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'RF']
five_factor = five_factor[0:699]
five_factor = five_factor.astype(float)
five_factor['date']=pd.to_datetime(five_factor["date"], format="%Y%m")
five_factor.set_index('date', inplace = True)
five_factor.head()

            MKT-RF   SMB   HML   RMW   CMA    RF
date
1963-07-01   -0.39 -0.44 -0.89  0.68 -1.23  0.27
1963-08-01    5.07 -0.75  1.68  0.36 -0.34  0.25
1963-09-01   -1.57 -0.55  0.08 -0.71  0.29  0.27
1963-10-01    2.53 -1.37 -0.14  2.80 -2.02  0.29
1963-11-01   -0.85 -0.89  1.81 -0.51  2.31  0.27

### Table 1

In [61]:
#Table 1 - Regressions
#regression on mkt-rf
Y = five_factor['MKT-RF']
X = five_factor[['SMB', 'HML', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
mkt = sm.OLS(Y, X2).fit()
mkt.summary2().tables[1]["Coef."]
mkt.summary2().tables[1]["t"]
mkt.summary2().tables[0][1][6]

#regression on smb
Y = five_factor['SMB']
X = five_factor[['MKT-RF', 'HML', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
smb = sm.OLS(Y, X2).fit()
smb.summary2().tables[1]["Coef."]
smb.summary2().tables[1]["t"]
smb.summary2().tables[0][1][6]

#regression on hml
Y = five_factor['HML']
X = five_factor[['MKT-RF', 'SMB', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
hml = sm.OLS(Y, X2).fit()
hml.summary2().tables[1]["Coef."]
hml.summary2().tables[1]["t"]
hml.summary2().tables[0][1][6]

#regression on rmw
Y = five_factor['RMW']
X = five_factor[['MKT-RF', 'SMB', 'HML', 'CMA']]
X2 = sm.add_constant(X)
rmw = sm.OLS(Y, X2).fit()
rmw.summary2().tables[1]["Coef."]
rmw.summary2().tables[1]["t"]
rmw.summary2().tables[0][1][6]

#regression on rmw
Y = five_factor['CMA']
X = five_factor[['MKT-RF', 'SMB', 'HML', 'RMW']]
X2 = sm.add_constant(X)
cma = sm.OLS(Y, X2).fit()
cma.summary2().tables[1]["Coef."]
cma.summary2().tables[1]["t"]
cma.summary2().tables[0][1][6]

const    0.804688
SMB      0.286308
HML      0.138923
RMW     -0.304303
CMA     -0.957614
Name: Coef., dtype: float64

'0.530'

In [161]:
mktv=mkt.summary2().tables[1]["Coef."]
mktv['MKT-RF']=""
mktv['R-squared']=mkt.summary2().tables[0][1][6]
mktt=mkt.summary2().tables[1]["t"]
mktt['MKT-RF']=""
mktt['R-squared']=""
mktd=pd.merge(pd.DataFrame(mktv),pd.DataFrame(mktt), on=mktv.index)
mktd.columns=['key','MKT-RF','t(mkt-rf)']
mktd=mktd.T
mktd=mktd.rename(columns=mktd.iloc[0], inplace=False)
mktd=mktd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'R-squared']]
mktd=mktd.iloc[1: , :]

smbv=smb.summary2().tables[1]["Coef."]
smbv['SMB']=""
smbv['R-squared']=smb.summary2().tables[0][1][6]
smbt=smb.summary2().tables[1]["t"]
smbt['SMB']=""
smbt['R-squared']=""
smbd=pd.merge(pd.DataFrame(smbv),pd.DataFrame(smbt), on=smbv.index)
smbd.columns=['key','SMB','t(SMB)']
smbd=smbd.T
smbd=smbd.rename(columns=smbd.iloc[0], inplace=False)
smbd=smbd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'R-squared']]
smbd=smbd.iloc[1: , :]

hmlv=hml.summary2().tables[1]["Coef."]
hmlv['HML']=""
hmlv['R-squared']=hml.summary2().tables[0][1][6]
hmlt=hml.summary2().tables[1]["t"]
hmlt['HML']=""
hmlt['R-squared']=""
hmld=pd.merge(pd.DataFrame(hmlv),pd.DataFrame(hmlt), on=hmlv.index)
hmld.columns=['key','HML','t(HML)']
hmld=hmld.T
hmld=hmld.rename(columns=hmld.iloc[0], inplace=False)
hmld=hmld[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'R-squared']]
hmld=hmld.iloc[1: , :]

rmwv=rmw.summary2().tables[1]["Coef."]
rmwv['RMW']=""
rmwv['R-squared']=rmw.summary2().tables[0][1][6]
rmwt=rmw.summary2().tables[1]["t"]
rmwt['RMW']=""
rmwt['R-squared']=""
rmwd=pd.merge(pd.DataFrame(rmwv),pd.DataFrame(rmwt), on=rmwv.index)
rmwd.columns=['key','RMW','t(RMW)']
rmwd=rmwd.T
rmwd=rmwd.rename(columns=rmwd.iloc[0], inplace=False)
rmwd=rmwd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'R-squared']]
rmwd=rmwd.iloc[1: , :]

cmav = cma.summary2().tables[1]["Coef."]
cmav['CMA']=""
cmav['R-squared']=cma.summary2().tables[0][1][6]
cmat=cma.summary2().tables[1]["t"]
cmat['CMA']=""
cmat['R-squared']=""
cmad=pd.merge(pd.DataFrame(cmav),pd.DataFrame(cmat), on=cmav.index)
cmad.columns=['key','CMA','t(CMA)']
cmad=cmad.T
cmad=cmad.rename(columns=cmad.iloc[0], inplace=False)
cmad=cmad[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA', 'R-squared']]
cmad=cmad.iloc[1: , :]

Table1 = pd.concat([mktd,smbd,hmld,rmwd,cmad])
Table1

,const,MKT-RF,SMB,HML,RMW,CMA,R-squared
MKT-RF,0.804732,,0.286306,0.138909,-0.304326,-0.957615,0.226
t(mkt-rf),5.280026,,5.412171,1.979227,-4.134345,-9.268905,
SMB,0.276261,0.141449,,0.129304,-0.446267,-0.161454,0.178
t(SMB),2.540254,5.412171,,2.626741,-9.005187,-2.103973,
HML,-0.094836,0.040407,0.076132,,0.202326,1.036238,0.472
t(HML),-1.132249,1.979227,2.626741,,5.129232,23.514173,
RMW,0.392178,-0.078986,-0.234442,0.180524,,-0.315332,0.175
t(RMW),5.042237,-4.134345,-9.005187,5.129232,,-5.786135,
CMA,0.260429,-0.115032,-0.039256,0.42792,-0.145945,,0.530
t(CMA),4.917494,-9.268905,-2.103973,23.514173,-5.786135,,

### Table 2

In [11]:
mom=pd.read_csv('F-F_Momentum_Factor.csv',skiprows = 13)
mom.columns=['date', 'UMD']
mom=mom[0:1137]
mom=mom.astype(float)
mom['date']=pd.to_datetime(mom["date"], format="%Y%m")

total = pd.merge(five_factor,mom, on='date')

#regression on mkt-rf
Y = total['MKT-RF']
X = total[['SMB', 'HML', 'RMW', 'CMA', 'UMD']]
X2 = sm.add_constant(X)
mkt = sm.OLS(Y, X2).fit()
mkt.summary2().tables[1]["Coef."]
mkt.summary2().tables[1]["t"]
mkt.summary2().tables[0][1][6]

#regression on smb
Y = total['SMB']
X = total[['MKT-RF', 'HML', 'RMW', 'CMA', 'UMD']]
X2 = sm.add_constant(X)
smb = sm.OLS(Y, X2).fit()
smb.summary2().tables[1]["Coef."]
smb.summary2().tables[1]["t"]
smb.summary2().tables[0][1][6]

#regression on hml
Y = total['HML']
X = total[['MKT-RF', 'SMB', 'RMW', 'CMA','UMD']]
X2 = sm.add_constant(X)
hml = sm.OLS(Y, X2).fit()
hml.summary2().tables[1]["Coef."]
hml.summary2().tables[1]["t"]
hml.summary2().tables[0][1][6]

#regression on rmw
Y = total['RMW']
X = total[['MKT-RF', 'SMB', 'HML', 'CMA','UMD']]
X2 = sm.add_constant(X)
rmw = sm.OLS(Y, X2).fit()
rmw.summary2().tables[1]["Coef."]
rmw.summary2().tables[1]["t"]
rmw.summary2().tables[0][1][6]

#regression on cma
Y = total['CMA']
X = total[['MKT-RF', 'SMB', 'HML', 'RMW','UMD']]
X2 = sm.add_constant(X)
cma = sm.OLS(Y, X2).fit()
cma.summary2().tables[1]["Coef."]
cma.summary2().tables[1]["t"]
cma.summary2().tables[0][1][6]

#regression on umd
Y = total['UMD']
X = total[['MKT-RF', 'SMB', 'HML', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
umd = sm.OLS(Y, X2).fit()
umd.summary2().tables[1]["Coef."]
umd.summary2().tables[1]["t"]
umd.summary2().tables[0][1][6]

'0.109'

In [180]:
mktv=mkt.summary2().tables[1]["Coef."]
mktv['MKT-RF']=""
mktv['R-squared']=mkt.summary2().tables[0][1][6]
mktt=mkt.summary2().tables[1]["t"]
mktt['MKT-RF']=""
mktt['R-squared']=""
mktd=pd.merge(pd.DataFrame(mktv),pd.DataFrame(mktt), on=mktv.index)
mktd.columns=['key','MKT-RF','t(mkt-rf)']
mktd=mktd.T
mktd=mktd.rename(columns=mktd.iloc[0], inplace=False)
mktd=mktd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD','R-squared']]
mktd=mktd.iloc[1: , :]

smbv=smb.summary2().tables[1]["Coef."]
smbv['SMB']=""
smbv['R-squared']=smb.summary2().tables[0][1][6]
smbt=smb.summary2().tables[1]["t"]
smbt['SMB']=""
smbt['R-squared']=""
smbd=pd.merge(pd.DataFrame(smbv),pd.DataFrame(smbt), on=smbv.index)
smbd.columns=['key','SMB','t(SMB)']
smbd=smbd.T
smbd=smbd.rename(columns=smbd.iloc[0], inplace=False)
smbd=smbd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD','R-squared']]
smbd=smbd.iloc[1: , :]

hmlv=hml.summary2().tables[1]["Coef."]
hmlv['HML']=""
hmlv['R-squared']=hml.summary2().tables[0][1][6]
hmlt=hml.summary2().tables[1]["t"]
hmlt['HML']=""
hmlt['R-squared']=""
hmld=pd.merge(pd.DataFrame(hmlv),pd.DataFrame(hmlt), on=hmlv.index)
hmld.columns=['key','HML','t(HML)']
hmld=hmld.T
hmld=hmld.rename(columns=hmld.iloc[0], inplace=False)
hmld=hmld[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD', 'R-squared']]
hmld=hmld.iloc[1: , :]

rmwv=rmw.summary2().tables[1]["Coef."]
rmwv['RMW']=""
rmwv['R-squared']=rmw.summary2().tables[0][1][6]
rmwt=rmw.summary2().tables[1]["t"]
rmwt['RMW']=""
rmwt['R-squared']=""
rmwd=pd.merge(pd.DataFrame(rmwv),pd.DataFrame(rmwt), on=rmwv.index)
rmwd.columns=['key','RMW','t(RMW)']
rmwd=rmwd.T
rmwd=rmwd.rename(columns=rmwd.iloc[0], inplace=False)
rmwd=rmwd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD', 'R-squared']]
rmwd=rmwd.iloc[1: , :]

cmav = cma.summary2().tables[1]["Coef."]
cmav['CMA']=""
cmav['R-squared']=cma.summary2().tables[0][1][6]
cmat=cma.summary2().tables[1]["t"]
cmat['CMA']=""
cmat['R-squared']=""
cmad=pd.merge(pd.DataFrame(cmav),pd.DataFrame(cmat), on=cmav.index)
cmad.columns=['key','CMA','t(CMA)']
cmad=cmad.T
cmad=cmad.rename(columns=cmad.iloc[0], inplace=False)
cmad=cmad[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD', 'R-squared']]
cmad=cmad.iloc[1: , :]

umdv = umd.summary2().tables[1]["Coef."]
umdv['UMD']=""
umdv['R-squared']=umd.summary2().tables[0][1][6]
umdt=umd.summary2().tables[1]["t"]
umdt['UMD']=""
umdt['R-squared']=""
umdd=pd.merge(pd.DataFrame(umdv),pd.DataFrame(umdt), on=umdv.index)
umdd.columns=['key','UMD','t(UMD)']
umdd=umdd.T
umdd=umdd.rename(columns=umdd.iloc[0], inplace=False)
umdd=umdd[['const','MKT-RF', 'SMB', 'HML', 'RMW', 'CMA','UMD', 'R-squared']]
umdd=umdd.iloc[1: , :]

Table2 = pd.concat([mktd,smbd,hmld,rmwd,cmad,umdd])
Table2

,const,MKT-RF,SMB,HML,RMW,CMA,UMD,R-squared
MKT-RF,0.892865,,0.285632,0.055841,-0.266443,-0.885115,-0.150704,0.245
t(mkt-rf),5.867093,,5.461487,0.772964,-3.63257,-8.540445,-4.12955,
SMB,0.262002,0.144471,,0.139613,-0.449899,-0.167789,0.019683,0.179
t(SMB),2.372379,5.461487,,2.730743,-9.032559,-2.172701,0.749523,
HML,0.010652,0.015426,0.076253,,0.215571,1.005863,-0.138213,0.510
t(HML),0.129985,0.772964,2.730743,,5.666118,23.580955,-7.394073,
RMW,0.352154,-0.070129,-0.234119,0.20539,,-0.328688,0.050496,0.184
t(RMW),4.46534,-3.63257,-9.032559,5.666118,,-6.032543,2.678229,
CMA,0.230277,-0.107589,-0.040323,0.442588,-0.151794,,0.037756,0.535
t(CMA),4.292138,-8.540445,-2.172701,23.580955,-6.032543,,2.949956,
UMD,0.713054,-0.159364,0.041152,-0.529065,0.202876,0.328465,,0.109
t(UMD),4.512184,-4.12955,0.749523,-7.394073,2.678229,2.949956,,

In [12]:
hml_dev = pd.read_excel('The Devil in HMLs Details Factors Monthly.xlsx',sheet_name='HML Devil',header=18,usecols=['DATE','USA'])
hml_dev.columns=['date','HML-DEV']
hml_dev['HML-DEV']=hml_dev['HML-DEV']*100
hml_dev['date']=pd.to_datetime(hml_dev["date"], format="%Y%m%d").dt.to_period('M').dt.to_timestamp()
devil = pd.merge(total,hml_dev,on='date')
devil.set_index('date', inplace = True)

In [104]:
devil.tail()

            MKT-RF   SMB   HML   RMW   CMA   RF   UMD   HML-DEV
date
2021-05-01    0.29  1.19  7.04  2.34  3.10  0.0  0.88  6.570220
2021-06-01    2.75 -0.25 -7.76 -2.14 -0.99  0.0  2.24 -5.025204
2021-07-01    1.27 -4.56 -1.75  5.36 -0.55  0.0 -2.29 -1.055571
2021-08-01    2.90 -0.79 -0.13 -0.25 -1.67  0.0  2.52 -1.105634
2021-09-01   -4.37  1.25  5.09 -1.94  2.08  0.0  1.57  5.404137

### Table 3

In [205]:
#regression on mkt-rf
Y = devil['MKT-RF']
X = devil[['SMB', 'HML-DEV', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
mkt = sm.OLS(Y, X2).fit()
mkt.summary2().tables[1]["Coef."]
mkt.summary2().tables[1]["t"]
mkt.summary2().tables[0][1][6]

#regression on smb
Y = devil['SMB']
X = devil[['MKT-RF', 'HML-DEV', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
smb = sm.OLS(Y, X2).fit()
smb.summary2().tables[1]["Coef."]
smb.summary2().tables[1]["t"]
smb.summary2().tables[0][1][6]

#regression on hml
Y = devil['HML-DEV']
X = devil[['MKT-RF', 'SMB', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
hml = sm.OLS(Y, X2).fit()
hml.summary2().tables[1]["Coef."]
hml.summary2().tables[1]["t"]
hml.summary2().tables[0][1][6]

#regression on rmw
Y = devil['RMW']
X = devil[['MKT-RF', 'SMB', 'HML-DEV', 'CMA']]
X2 = sm.add_constant(X)
rmw = sm.OLS(Y, X2).fit()
rmw.summary2().tables[1]["Coef."]
rmw.summary2().tables[1]["t"]
rmw.summary2().tables[0][1][6]

#regression on cma
Y = devil['CMA']
X = devil[['MKT-RF', 'SMB', 'HML-DEV', 'RMW']]
X2 = sm.add_constant(X)
cma = sm.OLS(Y, X2).fit()
cma.summary2().tables[1]["Coef."]
cma.summary2().tables[1]["t"]
cma.summary2().tables[0][1][6]

mktv=mkt.summary2().tables[1]["Coef."]
mktv['MKT-RF']=""
mktv['R-squared']=mkt.summary2().tables[0][1][6]
mktt=mkt.summary2().tables[1]["t"]
mktt['MKT-RF']=""
mktt['R-squared']=""
mktd=pd.merge(pd.DataFrame(mktv),pd.DataFrame(mktt), on=mktv.index)
mktd.columns=['key','MKT-RF','t(mkt-rf)']
mktd=mktd.T
mktd=mktd.rename(columns=mktd.iloc[0], inplace=False)
mktd=mktd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA', 'R-squared']]
mktd=mktd.iloc[1: , :]

smbv=smb.summary2().tables[1]["Coef."]
smbv['SMB']=""
smbv['R-squared']=smb.summary2().tables[0][1][6]
smbt=smb.summary2().tables[1]["t"]
smbt['SMB']=""
smbt['R-squared']=""
smbd=pd.merge(pd.DataFrame(smbv),pd.DataFrame(smbt), on=smbv.index)
smbd.columns=['key','SMB','t(SMB)']
smbd=smbd.T
smbd=smbd.rename(columns=smbd.iloc[0], inplace=False)
smbd=smbd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA', 'R-squared']]
smbd=smbd.iloc[1: , :]

hmlv=hml.summary2().tables[1]["Coef."]
hmlv['HML-DEV']=""
hmlv['R-squared']=hml.summary2().tables[0][1][6]
hmlt=hml.summary2().tables[1]["t"]
hmlt['HML-DEV']=""
hmlt['R-squared']=""
hmld=pd.merge(pd.DataFrame(hmlv),pd.DataFrame(hmlt), on=hmlv.index)
hmld.columns=['key','HML-DEV','t(HML-DEV)']
hmld=hmld.T
hmld=hmld.rename(columns=hmld.iloc[0], inplace=False)
hmld=hmld[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA', 'R-squared']]
hmld=hmld.iloc[1: , :]

rmwv=rmw.summary2().tables[1]["Coef."]
rmwv['RMW']=""
rmwv['R-squared']=rmw.summary2().tables[0][1][6]
rmwt=rmw.summary2().tables[1]["t"]
rmwt['RMW']=""
rmwt['R-squared']=""
rmwd=pd.merge(pd.DataFrame(rmwv),pd.DataFrame(rmwt), on=rmwv.index)
rmwd.columns=['key','RMW','t(RMW)']
rmwd=rmwd.T
rmwd=rmwd.rename(columns=rmwd.iloc[0], inplace=False)
rmwd=rmwd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA', 'R-squared']]
rmwd=rmwd.iloc[1: , :]

cmav = cma.summary2().tables[1]["Coef."]
cmav['CMA']=""
cmav['R-squared']=cma.summary2().tables[0][1][6]
cmat=cma.summary2().tables[1]["t"]
cmat['CMA']=""
cmat['R-squared']=""
cmad=pd.merge(pd.DataFrame(cmav),pd.DataFrame(cmat), on=cmav.index)
cmad.columns=['key','CMA','t(CMA)']
cmad=cmad.T
cmad=cmad.rename(columns=cmad.iloc[0], inplace=False)
cmad=cmad[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA', 'R-squared']]
cmad=cmad.iloc[1: , :]

Table3 = pd.concat([mktd,smbd,hmld,rmwd,cmad])
Table3

,const,MKT-RF,SMB,HML-DEV,RMW,CMA,R-squared
MKT-RF,0.797248,,0.277833,0.190843,-0.281598,-0.995681,0.238
t(mkt-rf),5.274871,,5.302885,3.886802,-3.921418,-11.339316,
SMB,0.271504,0.140162,,0.064909,-0.425521,-0.093874,0.174
t(SMB),2.490968,5.302885,,1.845804,-8.68915,-1.384452,
HML-DEV,-0.09526,0.111634,0.075262,,0.051018,1.020985,0.288
t(HML-DEV),-0.808426,3.886802,1.845804,,0.919345,16.468249,
RMW,0.391074,-0.07698,-0.230581,0.023842,,-0.15731,0.145
t(RMW),4.936993,-3.921418,-8.68915,0.919345,,-3.170013,
CMA,0.310229,-0.156991,-0.02934,0.275205,-0.090733,,0.392
t(CMA),5.165094,-11.339316,-1.384452,16.468249,-3.170013,,

### Table 4

In [206]:
#regression on mkt-rf
Y = devil['MKT-RF']
X = devil[['SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']]
X2 = sm.add_constant(X)
mkt = sm.OLS(Y, X2).fit()
mkt.summary2().tables[1]["Coef."]
mkt.summary2().tables[1]["t"]
mkt.summary2().tables[0][1][6]

#regression on smb
Y = devil['SMB']
X = devil[['MKT-RF', 'HML-DEV', 'RMW', 'CMA', 'UMD']]
X2 = sm.add_constant(X)
smb = sm.OLS(Y, X2).fit()
smb.summary2().tables[1]["Coef."]
smb.summary2().tables[1]["t"]
smb.summary2().tables[0][1][6]

#regression on hml
Y = devil['HML-DEV']
X = devil[['MKT-RF', 'SMB', 'RMW', 'CMA','UMD']]
X2 = sm.add_constant(X)
hml = sm.OLS(Y, X2).fit()
hml.summary2().tables[1]["Coef."]
hml.summary2().tables[1]["t"]
hml.summary2().tables[0][1][6]

#regression on rmw
Y = devil['RMW']
X = devil[['MKT-RF', 'SMB', 'HML-DEV', 'CMA','UMD']]
X2 = sm.add_constant(X)
rmw = sm.OLS(Y, X2).fit()
rmw.summary2().tables[1]["Coef."]
rmw.summary2().tables[1]["t"]
rmw.summary2().tables[0][1][6]

#regression on cma
Y = devil['CMA']
X = devil[['MKT-RF', 'SMB', 'HML-DEV', 'RMW','UMD']]
X2 = sm.add_constant(X)
cma = sm.OLS(Y, X2).fit()
cma.summary2().tables[1]["Coef."]
cma.summary2().tables[1]["t"]
cma.summary2().tables[0][1][6]

#regression on umd
Y = devil['UMD']
X = devil[['MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
umd = sm.OLS(Y, X2).fit()
umd.summary2().tables[1]["Coef."]
umd.summary2().tables[1]["t"]
umd.summary2().tables[0][1][6]

mktv=mkt.summary2().tables[1]["Coef."]
mktv['MKT-RF']=""
mktv['R-squared']=mkt.summary2().tables[0][1][6]
mktt=mkt.summary2().tables[1]["t"]
mktt['MKT-RF']=""
mktt['R-squared']=""
mktd=pd.merge(pd.DataFrame(mktv),pd.DataFrame(mktt), on=mktv.index)
mktd.columns=['key','MKT-RF','t(mkt-rf)']
mktd=mktd.T
mktd=mktd.rename(columns=mktd.iloc[0], inplace=False)
mktd=mktd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD','R-squared']]
mktd=mktd.iloc[1: , :]

smbv=smb.summary2().tables[1]["Coef."]
smbv['SMB']=""
smbv['R-squared']=smb.summary2().tables[0][1][6]
smbt=smb.summary2().tables[1]["t"]
smbt['SMB']=""
smbt['R-squared']=""
smbd=pd.merge(pd.DataFrame(smbv),pd.DataFrame(smbt), on=smbv.index)
smbd.columns=['key','SMB','t(SMB)']
smbd=smbd.T
smbd=smbd.rename(columns=smbd.iloc[0], inplace=False)
smbd=smbd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD','R-squared']]
smbd=smbd.iloc[1: , :]

hmlv=hml.summary2().tables[1]["Coef."]
hmlv['HML-DEV']=""
hmlv['R-squared']=hml.summary2().tables[0][1][6]
hmlt=hml.summary2().tables[1]["t"]
hmlt['HML-DEV']=""
hmlt['R-squared']=""
hmld=pd.merge(pd.DataFrame(hmlv),pd.DataFrame(hmlt), on=hmlv.index)
hmld.columns=['key','HML-DEV','t(HML-DEV)']
hmld=hmld.T
hmld=hmld.rename(columns=hmld.iloc[0], inplace=False)
hmld=hmld[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD', 'R-squared']]
hmld=hmld.iloc[1: , :]

rmwv=rmw.summary2().tables[1]["Coef."]
rmwv['RMW']=""
rmwv['R-squared']=rmw.summary2().tables[0][1][6]
rmwt=rmw.summary2().tables[1]["t"]
rmwt['RMW']=""
rmwt['R-squared']=""
rmwd=pd.merge(pd.DataFrame(rmwv),pd.DataFrame(rmwt), on=rmwv.index)
rmwd.columns=['key','RMW','t(RMW)']
rmwd=rmwd.T
rmwd=rmwd.rename(columns=rmwd.iloc[0], inplace=False)
rmwd=rmwd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD', 'R-squared']]
rmwd=rmwd.iloc[1: , :]

cmav = cma.summary2().tables[1]["Coef."]
cmav['CMA']=""
cmav['R-squared']=cma.summary2().tables[0][1][6]
cmat=cma.summary2().tables[1]["t"]
cmat['CMA']=""
cmat['R-squared']=""
cmad=pd.merge(pd.DataFrame(cmav),pd.DataFrame(cmat), on=cmav.index)
cmad.columns=['key','CMA','t(CMA)']
cmad=cmad.T
cmad=cmad.rename(columns=cmad.iloc[0], inplace=False)
cmad=cmad[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD', 'R-squared']]
cmad=cmad.iloc[1: , :]

umdv = umd.summary2().tables[1]["Coef."]
umdv['UMD']=""
umdv['R-squared']=umd.summary2().tables[0][1][6]
umdt=umd.summary2().tables[1]["t"]
umdt['UMD']=""
umdt['R-squared']=""
umdd=pd.merge(pd.DataFrame(umdv),pd.DataFrame(umdt), on=umdv.index)
umdd.columns=['key','UMD','t(UMD)']
umdd=umdd.T
umdd=umdd.rename(columns=umdd.iloc[0], inplace=False)
umdd=umdd[['const','MKT-RF', 'SMB', 'HML-DEV', 'RMW', 'CMA','UMD', 'R-squared']]
umdd=umdd.iloc[1: , :]

Table4 = pd.concat([mktd,smbd,hmld,rmwd,cmad,umdd])
Table4

,const,MKT-RF,SMB,HML-DEV,RMW,CMA,UMD,R-squared
MKT-RF,0.875553,,0.28554,0.057385,-0.260263,-0.880799,-0.127809,0.245
t(mkt-rf),5.683529,,5.45888,0.778374,-3.609681,-8.847873,-2.420089,
SMB,0.218393,0.144385,,0.144358,-0.434426,-0.157813,0.07739,0.179
t(SMB),1.954106,5.45888,,2.76759,-8.856989,-2.120031,2.058376,
HML-DEV,0.311862,0.015222,0.075728,,0.102137,0.903754,-0.533422,0.680
t(HML-DEV),3.883699,0.778374,2.76759,,2.739664,21.621824,-29.122394,
RMW,0.334068,-0.070909,-0.234073,0.104906,,-0.22119,0.078844,0.155
t(RMW),4.110203,-3.609681,-8.856989,2.739664,,-4.083245,2.864993,
CMA,0.113911,-0.115236,-0.040832,0.445747,-0.106215,,0.212569,0.500
t(CMA),2.004058,-8.847873,-2.120031,21.621824,-4.083245,,12.216234,
UMD,0.66495,-0.065571,0.07852,-1.031688,0.148467,0.833566,,0.568
t(UMD),6.043813,-2.420089,2.058376,-29.122394,2.864993,12.216234,,

In [51]:
portfolio25 = pd.read_csv('25_Portfolios_5x5.csv', skiprows=15, nrows =1144)
portfolio25.rename(columns = {'Unnamed: 0' :'date'  }, inplace= True)
portfolio25['date']=pd.to_datetime(portfolio25["date"], format="%Y%m")
portfolio25 = portfolio25[(portfolio25['date'] >= pd.to_datetime('196307', format="%Y%m"))]
portfolio25.set_index('date', inplace = True)
portfolio25.drop(portfolio25.tail(1).index,inplace=True)
portfolio25.tail()

,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,ME2 BM5,...,ME4 BM1,ME4 BM2,ME4 BM3,ME4 BM4,ME4 BM5,BIG LoBM,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM
date,,,,,,,,,,,,,,,,,,,,,
2021-05-01,1.4358,0.5285,0.7486,2.3463,10.4483,-2.4340,0.1611,0.5692,2.6063,7.3152,...,-1.9889,0.0367,2.1225,3.7037,4.4815,-1.3830,0.7609,3.3797,3.6626,8.0384
2021-06-01,8.6902,5.1847,1.0202,-0.4778,3.7169,6.6363,3.5228,1.3767,-2.0188,1.1213,...,5.1402,0.2436,-1.0576,-3.8628,-4.6390,5.7328,1.4829,-2.2818,-2.3452,-3.7225
2021-07-01,-10.1722,-7.6929,-3.6097,-4.7524,-1.5492,-7.4616,-3.2841,-1.7334,-2.1717,-6.0351,...,-0.7491,1.8909,-1.2862,1.3608,-4.2888,3.3015,3.1933,0.4040,-1.5415,-3.4379
2021-08-01,2.5319,5.5794,4.0683,1.8322,3.9693,1.9219,2.3791,1.2297,1.5206,2.4331,...,3.2077,1.5669,1.6435,3.2307,5.0117,3.3117,4.1280,0.5554,1.2868,4.3102
2021-09-01,-5.1961,-4.3855,-3.3635,-0.8426,0.1511,-5.3511,-4.1155,-3.6209,-0.4379,3.3170,...,-4.3556,-5.0464,-2.1698,-4.5869,1.4868,-5.2780,-6.2358,-4.3843,-0.7534,0.6721

In [79]:
Y = portfolio25['BIG HiBM']
X = five_factor[['MKT-RF','SMB', 'HML', 'RMW', 'CMA']]
X2 = sm.add_constant(X)
mkt = sm.OLS(Y, X2).fit()
alphadf = pd.DataFrame(mkt.summary2().tables[1]["Coef."])
c2st = 'BIG HiBM'
alphadf.rename(columns = {'Coef.' : f"{c2st}"}, inplace= True)
alphadf.head()
#mkt.summary2().tables[1]["t"]

        BIG HiBM
const   0.328005
MKT-RF  1.072273
SMB    -0.155189
HML     1.061153
RMW    -0.183002

In [89]:
count = 0 
for col in portfolio25:
    Y = portfolio25[col]
    X = five_factor[['MKT-RF','SMB', 'HML', 'RMW', 'CMA']]
    X2 = sm.add_constant(X)
    mkt = sm.OLS(Y, X2).fit()
    alphadf = pd.DataFrame(mkt.summary2().tables[1]["Coef."])
    alphadf.rename(columns = {'Coef.' : f"{col} Alpha"}, inplace= True)
    tstatdf = pd.DataFrame(mkt.summary2().tables[1]["t"])
    tstatdf.rename(columns = {'t' : f"{col} T-stat"}, inplace= True)
    if count == 0:
        mergeddataalpha = alphadf
        mergeddatatstat = tstatdf
        count +=1
    else: 
        mergeddataalpha = mergeddataalpha.join(alphadf)
        mergeddatatstat = mergeddatatstat.join(tstatdf)
mergeddatatstat.head()

,SMALL LoBM T-stat,ME1 BM2 T-stat,ME1 BM3 T-stat,ME1 BM4 T-stat,SMALL HiBM T-stat,ME2 BM1 T-stat,ME2 BM2 T-stat,ME2 BM3 T-stat,ME2 BM4 T-stat,ME2 BM5 T-stat,...,ME4 BM1 T-stat,ME4 BM2 T-stat,ME4 BM3 T-stat,ME4 BM4 T-stat,ME4 BM5 T-stat,BIG LoBM T-stat,ME5 BM2 T-stat,ME5 BM3 T-stat,ME5 BM4 T-stat,BIG HiBM T-stat
const,1.203613,7.602033,7.049245,10.196013,6.574886,4.654111,7.136075,6.701606,7.740830,6.708972,...,9.136320,3.565100,3.886249,5.801383,3.746995,11.463909,5.333711,4.850594,2.276867,3.379339
MKT-RF,49.327623,54.590524,72.572576,69.305809,51.480550,72.421398,78.574676,74.656653,78.031647,78.776608,...,70.993048,70.059890,65.273915,61.891471,57.873421,96.194562,74.583341,59.750608,64.826407,45.237507
SMB,41.796834,49.859154,59.167074,58.757923,40.786483,45.766634,51.379147,43.421101,43.149303,45.426107,...,16.848923,12.772522,10.116952,10.406476,10.785017,-13.217436,-7.051645,-8.535871,-7.925988,-4.601945
HML,-10.176751,-5.445868,5.817615,12.661631,12.095549,-15.493918,-1.073304,11.509633,18.729689,24.972842,...,-14.532023,2.409088,11.729472,17.656961,21.538845,-15.837024,1.260236,9.021042,24.811305,24.145762
RMW,-12.075975,-11.778050,-2.271264,-1.729919,0.294860,-6.209476,2.839215,8.597563,3.568324,1.168237,...,-5.203105,6.750511,6.774309,2.097967,0.607426,9.310576,6.529256,2.125511,1.491982,-3.933361

In [90]:
mergeddataalpha.head()

,SMALL LoBM Alpha,ME1 BM2 Alpha,ME1 BM3 Alpha,ME1 BM4 Alpha,SMALL HiBM Alpha,ME2 BM1 Alpha,ME2 BM2 Alpha,ME2 BM3 Alpha,ME2 BM4 Alpha,ME2 BM5 Alpha,...,ME4 BM1 Alpha,ME4 BM2 Alpha,ME4 BM3 Alpha,ME4 BM4 Alpha,ME4 BM5 Alpha,BIG LoBM Alpha,ME5 BM2 Alpha,ME5 BM3 Alpha,ME5 BM4 Alpha,BIG HiBM Alpha
const,0.104719,0.535143,0.367317,0.530967,0.505985,0.287566,0.373401,0.358042,0.386931,0.375749,...,0.550217,0.225276,0.255524,0.394303,0.302795,0.477983,0.293469,0.319754,0.146426,0.328005
MKT-RF,1.048058,0.938458,0.923481,0.881382,0.967499,1.092762,1.004054,0.974049,0.952521,1.077450,...,1.044085,1.081112,1.048091,1.027277,1.142096,0.979463,1.002149,0.961879,1.018098,1.072273
SMB,1.263433,1.219429,1.071149,1.063102,1.090530,0.982476,0.934061,0.805985,0.749362,0.883933,...,0.352538,0.280409,0.231112,0.245739,0.302802,-0.191469,-0.134802,-0.195497,-0.177094,-0.155189
HML,-0.400899,-0.173578,0.137256,0.298548,0.421467,-0.433462,-0.025429,0.278423,0.423901,0.633284,...,-0.396257,0.068926,0.349195,0.543380,0.788091,-0.298980,0.031396,0.269256,0.722467,1.061153
RMW,-0.503620,-0.397427,-0.056730,-0.043182,0.010877,-0.183908,0.071213,0.220178,0.085498,0.031363,...,-0.150200,0.204467,0.213506,0.068351,0.023529,0.186080,0.172203,0.067163,0.045993,-0.183002

In [102]:
X = devil[['MKT-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']]
print(X)

     MKT-RF   SMB   HML-DEV   RMW   CMA   UMD
0     -0.39 -0.44 -0.592258  0.68 -1.23  0.97
1      5.07 -0.75  0.280529  0.36 -0.34  1.01
2     -1.57 -0.55  0.265286 -0.71  0.29  0.19
3      2.53 -1.37 -2.112853  2.80 -2.02  3.12
4     -0.85 -0.89  0.907441 -0.51  2.31 -0.74
..      ...   ...       ...   ...   ...   ...
694    0.29  1.19  6.570220  2.34  3.10  0.88
695    2.75 -0.25 -5.025204 -2.14 -0.99  2.24
696    1.27 -4.56 -1.055571  5.36 -0.55 -2.29
697    2.90 -0.79 -1.105634 -0.25 -1.67  2.52
698   -4.37  1.25  5.404137 -1.94  2.08  1.57

[699 rows x 6 columns]

In [105]:
count = 0 
for col in portfolio25:
    Y = portfolio25[col]
    X = devil[['MKT-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']]
    X2 = sm.add_constant(X)
    mkt = sm.OLS(Y, X2).fit()
    alphadf = pd.DataFrame(mkt.summary2().tables[1]["Coef."])
    alphadf.rename(columns = {'Coef.' : f"{col} Alpha"}, inplace= True)
    tstatdf = pd.DataFrame(mkt.summary2().tables[1]["t"])
    tstatdf.rename(columns = {'t' : f"{col} T-stat"}, inplace= True)
    if count == 0:
        mergeddataalpha = alphadf
        mergeddatatstat = tstatdf
        count +=1
    else: 
        mergeddataalpha = mergeddataalpha.join(alphadf)
        mergeddatatstat = mergeddatatstat.join(tstatdf)
mergeddatatstat.head()

,SMALL LoBM T-stat,ME1 BM2 T-stat,ME1 BM3 T-stat,ME1 BM4 T-stat,SMALL HiBM T-stat,ME2 BM1 T-stat,ME2 BM2 T-stat,ME2 BM3 T-stat,ME2 BM4 T-stat,ME2 BM5 T-stat,...,ME4 BM1 T-stat,ME4 BM2 T-stat,ME4 BM3 T-stat,ME4 BM4 T-stat,ME4 BM5 T-stat,BIG LoBM T-stat,ME5 BM2 T-stat,ME5 BM3 T-stat,ME5 BM4 T-stat,BIG HiBM T-stat
const,2.352402,7.481948,6.519416,7.926272,5.019729,6.211937,7.834258,5.825511,5.146317,3.258397,...,10.179636,3.785140,2.771470,3.706762,2.009420,12.775774,4.937438,3.183329,-0.166134,1.257295
MKT-RF,46.543323,53.939551,71.074234,65.173459,49.211841,66.567392,77.686085,71.061710,69.859252,69.585904,...,68.226599,69.108964,63.965068,58.817487,52.061768,91.767703,73.803376,60.959542,57.941012,38.313829
SMB,39.939792,49.380803,58.942677,55.869054,39.671784,42.587826,51.826519,42.395912,39.435533,40.835908,...,16.195853,12.928139,10.190306,10.231514,10.386051,-12.903122,-7.211659,-9.072425,-6.831709,-3.353464
HML-DEV,-6.714843,-3.311592,4.137347,8.343934,9.004847,-11.165161,-2.075213,7.001674,11.901827,17.984197,...,-11.841216,1.356729,10.176132,14.365532,14.253264,-13.328379,2.549258,11.375975,17.963425,13.963054
RMW,-13.009438,-12.727980,-1.451429,-0.138960,1.788169,-7.615788,3.030216,10.123828,5.516851,3.766540,...,-6.836768,7.354293,8.313628,4.144579,3.341050,7.363612,6.650308,2.939317,4.243727,-0.492704

In [106]:
mergeddataalpha.head()

,SMALL LoBM Alpha,ME1 BM2 Alpha,ME1 BM3 Alpha,ME1 BM4 Alpha,SMALL HiBM Alpha,ME2 BM1 Alpha,ME2 BM2 Alpha,ME2 BM3 Alpha,ME2 BM4 Alpha,ME2 BM5 Alpha,...,ME4 BM1 Alpha,ME4 BM2 Alpha,ME4 BM3 Alpha,ME4 BM4 Alpha,ME4 BM5 Alpha,BIG LoBM Alpha,ME5 BM2 Alpha,ME5 BM3 Alpha,ME5 BM4 Alpha,BIG HiBM Alpha
const,0.218066,0.542969,0.350383,0.447507,0.409385,0.420085,0.417459,0.329666,0.291753,0.209797,...,0.647106,0.244107,0.187291,0.267696,0.181196,0.564918,0.277691,0.208435,-0.012066,0.145324
MKT-RF,1.039930,0.943492,0.920699,0.886895,0.967369,1.085032,0.997768,0.969274,0.954582,1.079912,...,1.045365,1.074247,1.041888,1.023823,1.131536,0.978045,1.000478,0.962060,1.014286,1.067400
SMB,1.254941,1.214674,1.073757,1.069162,1.096667,0.976196,0.936072,0.813215,0.757788,0.891210,...,0.348970,0.282603,0.233419,0.250454,0.317446,-0.193390,-0.137479,-0.201351,-0.168180,-0.131382
HML-DEV,-0.291334,-0.112480,0.104072,0.220486,0.343722,-0.353390,-0.051756,0.185447,0.315799,0.541959,...,-0.352305,0.040952,0.321862,0.485566,0.601550,-0.275838,0.067105,0.348624,0.610621,0.755371
RMW,-0.556881,-0.426528,-0.036021,-0.003623,0.067342,-0.237822,0.074562,0.264553,0.144423,0.111987,...,-0.200688,0.219012,0.259433,0.138215,0.139120,0.150355,0.172715,0.088872,0.142324,-0.026297

In [5]:
industry10 = pd.read_csv('10_Industry_Portfolios.csv', skiprows=11, nrows =1143)
industry10.rename(columns = {'Unnamed: 0' :'date'  }, inplace= True)
industry10['date']=pd.to_datetime(industry10["date"], format="%Y%m")
industry10 = industry10[(industry10['date'] >= pd.to_datetime('196307', format="%Y%m"))]
industry10.set_index('date', inplace = True)
industry10.tail()

,NoDur,Durbl,Manuf,Enrgy,HiTec,Telcm,Shops,Hlth,Utils,Other
date,,,,,,,,,,
2021-05-01,1.93,-5.26,2.70,6.13,-0.87,-0.83,-2.21,0.02,-1.17,2.94
2021-06-01,-0.74,5.66,-0.80,5.50,6.94,-0.12,2.84,4.28,-1.42,-2.46
2021-07-01,0.20,-0.69,1.34,-8.52,3.42,0.31,0.26,3.15,2.94,-0.38
2021-08-01,-0.29,1.73,0.53,-1.35,4.68,1.40,2.39,2.85,3.22,2.48
2021-09-01,-4.57,2.84,-5.77,10.63,-6.27,-5.65,-4.20,-5.94,-4.77,-2.35

In [8]:
count = 0 
for col in industry10:
    Y = industry10[col]
    X = five_factor[['MKT-RF','SMB', 'HML', 'RMW', 'CMA']]
    X2 = sm.add_constant(X)
    mkt = sm.OLS(Y, X2).fit()
    alphadf = pd.DataFrame(mkt.summary2().tables[1]["Coef."])
    alphadf.rename(columns = {'Coef.' : f"{col} Alpha"}, inplace= True)
    tstatdf = pd.DataFrame(mkt.summary2().tables[1]["t"])
    tstatdf.rename(columns = {'t' : f"{col} T-stat"}, inplace= True)
    if count == 0:
        mergeddataalpha = alphadf
        mergeddatatstat = tstatdf
        count +=1
    else: 
        mergeddataalpha = mergeddataalpha.join(alphadf)
        mergeddatatstat = mergeddatatstat.join(tstatdf)
mergeddatatstat.head()

,NoDur T-stat,Durbl T-stat,Manuf T-stat,Enrgy T-stat,HiTec T-stat,Telcm T-stat,Shops T-stat,Hlth T-stat,Utils T-stat,Other T-stat
const,3.482179,0.040861,3.095189,1.202490,7.836467,3.939515,3.472891,4.929881,2.640241,2.794606
MKT-RF,44.390337,33.955232,71.494198,23.618427,41.497614,29.596793,42.915283,31.415318,21.481190,71.806044
SMB,2.331716,3.991183,5.020125,-0.695146,2.342600,-6.522698,6.320986,-3.067544,-3.880026,3.968137
HML,-1.242809,4.497059,3.543717,3.783065,-6.789948,2.101751,-1.566032,-7.943778,3.665492,16.111034
RMW,14.620672,3.133566,10.789178,2.166961,-8.166052,-4.516731,9.846698,5.745672,2.443397,4.037686

In [9]:
mergeddataalpha.head()

,NoDur Alpha,Durbl Alpha,Manuf Alpha,Enrgy Alpha,HiTec Alpha,Telcm Alpha,Shops Alpha,Hlth Alpha,Utils Alpha,Other Alpha
const,0.283770,0.006235,0.191187,0.205261,0.803127,0.455525,0.331345,0.561025,0.321413,0.179319
MKT-RF,0.883409,1.265248,1.078449,0.984541,1.038592,0.835741,0.999907,0.873062,0.638610,1.125186
SMB,0.066018,0.211585,0.107735,-0.041226,0.083413,-0.262041,0.209530,-0.121285,-0.164107,0.088464
HML,-0.045857,0.310691,0.099110,0.292386,-0.315079,0.110037,-0.067652,-0.409318,0.202041,0.468077
RMW,0.571119,0.229189,0.319450,0.177305,-0.401162,-0.250344,0.450323,0.313423,0.142580,0.124189

In [14]:
count = 0 
for col in industry10:
    Y = industry10[col]
    X = devil[['MKT-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']]
    X2 = sm.add_constant(X)
    mkt = sm.OLS(Y, X2).fit()
    alphadf = pd.DataFrame(mkt.summary2().tables[1]["Coef."])
    alphadf.rename(columns = {'Coef.' : f"{col} Alpha"}, inplace= True)
    tstatdf = pd.DataFrame(mkt.summary2().tables[1]["t"])
    tstatdf.rename(columns = {'t' : f"{col} T-stat"}, inplace= True)
    if count == 0:
        mergeddataalpha = alphadf
        mergeddatatstat = tstatdf
        count +=1
    else: 
        mergeddataalpha = mergeddataalpha.join(alphadf)
        mergeddatatstat = mergeddatatstat.join(tstatdf)
mergeddatatstat.head()

,NoDur T-stat,Durbl T-stat,Manuf T-stat,Enrgy T-stat,HiTec T-stat,Telcm T-stat,Shops T-stat,Hlth T-stat,Utils T-stat,Other T-stat
const,3.916382,0.456005,3.265615,0.046351,8.923885,3.751232,4.410824,5.724557,1.417384,1.619747
MKT-RF,43.858415,34.232108,70.297501,23.914381,40.588799,29.235497,42.374937,31.700803,21.820622,65.486709
SMB,2.471360,4.087815,5.223820,-1.023597,2.363789,-6.893248,6.574022,-3.046814,-4.219332,4.186627
HML-DEV,-2.466000,5.832759,1.436962,6.674387,-6.683325,4.477013,-3.331058,-8.175558,6.167653,9.290731
RMW,14.881159,4.069596,11.627687,2.289424,-8.860788,-4.547852,10.225262,4.994645,2.557977,6.001959